project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/mark-hamilton28
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

